### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [ejvkamp/teaCozy#3]
Meets Expectations

Good job on this project it looks close to spec. I only had one "issue" which was a quick fix, you just need to set the justify content differently and you are all set.  One of the biggest takeaways for this project is to use flex and  you did that very well, great job. Next try to challenge yourself by adding a menu, if you need idea try using themeforest.com or your local cafe! Keep up the good work. You might also want a contact form, you can find a easy example to follow on w3schools.com

**Comment by ejvkamp** [comment]
Thanks very much for your feedback and the advice for further improvements.
